docs: refine the tutorial for lime and add tutorial for attributions methods
xai4space/meteors pull request #128
Opened 2024-11-14 15:15 UTC by WolodjaZ

2024-11-14 17:40 UTC, Fersoil requested changes
There are needed some changes pointed by Przemek, I would also add more detailed descriptions for the attribute methods showcase

2024-11-14 17:40 UTC, Fersoil commented on examples/hyperview_challenge/attr_showcase.ipynb
In general, good job. Apart from Przemek's comments, I would add:
- a little bit shorter title
- I like a bit more the intro in the LIME tutorial - I would make it consistent accross the tutorials
- better explanation of HyperNoiseTunnel - this is extra created by us, so I would dwell into it a little bit more
- The tutorial lacks explanations of the figures - for the LIME one, you proposed a very nice solution to describe the chart contents. Here I would do it at least once
- consider moving the function in the first section to a separate file - the user won't read the code anyway and it clutters the tutorial
- consider adding a better description of a parameters in an `attribute` method call

2024-11-14 17:40 UTC, Fersoil commented on examples/hyperview_challenge/lime.ipynb
Looks good. Again Przemek is right about reducing the block of wavelength listing. From my perspective you could also move the model download into a separate file

2024-11-15 14:46 UTC, WolodjaZ commented
@Fersoil check if the file `wavelengths` in segmentation data example is correct :)

2024-11-16 00:48 UTC, Fersoil approved these changes
only one small issue with attr tutorial, but good to merge

2024-11-17 23:54 UTC, merged