band mask created by hand
xai4space/meteors pull request #22
Opened 2024-06-25 17:14 UTC by Fersoil

Simplified the flow of creating a band mask - for now the core feature of our package, since spectral analysis is something new.

To create a band mask, users may pass list of bands, ranges of wavelengths, ranges of indices of wavelengths and dictionary containing simple list of indices. 

Band names are matched using `spyndex` library

I guess, I could describe this feature more thoroughly - create a diagram, some use-cases or better description

2024-07-02 15:16 UTC, WolodjaZ commented on src/meteors/lime.py
> +        if isinstance(segment_name, str):
Okay I think we can do type validation in private functions only If not:
`
- the code is performance-sensitive, additional type checks could introduce unnecessary overhead.
- the public methods thoroughly check types and there is no reasonable way incorrect types could be passed to private methods, additional checks might be redundant.
`

2024-07-02 20:05 UTC, Fersoil commented on src/meteors/lime.py
> +import loguru
As far as I remember `kw_only` in `Field` was added by you, I don't really know if we need to use this parameter

2024-07-02 20:22 UTC, Fersoil commented on src/meteors/lime.py
> +import loguru
`loguru.logger` changed for `logger`

2024-07-02 20:25 UTC, Fersoil commented on src/meteors/lime.py
> -        band_names: list[str | Sequence[str]] | dict[tuple[str, ...] | str, int],
changed each `Sequence` for `list`

2024-07-02 20:30 UTC, Fersoil commented on src/meteors/lime.py
> +            band_groups = Lime.__get_band_groups_from_band_ranges_indices(
Modified to more open approach with single underscore

2024-07-02 21:01 UTC, Fersoil commented on src/meteors/lime.py
> +        if isinstance(segment_name, str):
I believe that public functions should do the checks, the performance aspect is also relevant

2024-07-03 09:03 UTC, WolodjaZ commented on src/meteors/lime.py
> +import loguru
Interesting I have never used `kw_only` so lets remove it.

2024-07-03 13:34 UTC, WolodjaZ approved these changes

2024-07-05 10:09 UTC, WolodjaZ requested changes

2024-07-05 10:09 UTC, WolodjaZ commented on src/meteors/lime.py
> +            band_ranges_wavelengths, dict_labels_to_segment_ids = Lime._get_band_ranges_wavelengths_from_band_names(
Mypy gives me:
`src/meteors/lime.py:316: error: Incompatible types in assignment (expression has type "dict[Union[str, tuple[str, ...]], list[tuple[float, float]]]", variable has type "Optional[dict[Union[str, tuple[str, ...]], Union[Iterable[tuple[float, float]], tuple[float, float]]]]")  [assignment]
Found 1 error in 1 file (checked 12 source files)`

2024-07-05 10:09 UTC, WolodjaZ commented on src/meteors/lime.py
> +        image: Image,
variable image is not used in the function

2024-07-05 10:15 UTC, WolodjaZ commented on src/meteors/lime.py
> +            band_ranges_wavelengths, dict_labels_to_segment_ids = Lime._get_band_ranges_wavelengths_from_band_names(
ignoring as @Fersoil decided

2024-07-09 12:38 UTC, WolodjaZ requested changes

2024-07-09 12:38 UTC, WolodjaZ commented on src/meteors/lime.py
> +        image: Image,
@Fersoil still the variable image is not used.

2024-07-09 12:38 UTC, WolodjaZ commented on src/meteors/lime.py
> +        segments_list = []
@Fersoil is there a need for empty list initialization if it is always assigned?

2024-07-11 10:10 UTC, WolodjaZ approved these changes

2024-07-11 13:04 UTC, merged